### ISSUE TITLE
[Greasemonkey-Stylish plugin] Using User Styles also

### ISSUE THREAD

**Issue by D0ve** [QupZilla/qupzilla-plugins#29]
if Greasemonkey plugin can handle User Styles (with modifications in its)-
Why not to make it with auto support\install\uninstall for User Styles also !!!
the name could be renewed to Greasemonkey-Stylish or smth similar)
Many thanks in advance for implementation!!!

**Comment by ShalokShalom** [comment]
Hi there ^-^

If you are still interested - i am. 

My eyes are very sensitive to light, so i become used to dark themes. 

Userscripts are nice, while they load the theme after it page is already rendered. That means always a shocking white screen between switching the pages. Stylish is outdated and unmaintained, Stylus is its successor: 

https://github.com/openstyles/stylus

Thanks a lot in advance
