### ISSUE TITLE
Theme update + new one

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla-plugins#46]
Hi, i would like to make some improvements and additions in [Fergris](https://github.com/QupZilla/qupzilla-plugins/tree/master/themes/fergris) theme! All files are in the [tarball](https://yadi.sk/d/HJsR3SA0eEU74) (incl. unchanged). Some images looks the same, but it have small changes, so please replace it! 

And just one more [theme](https://yadi.sk/d/nUjVBk5DeEU9Q):
![hjsr3sa0eeu74](https://cloud.githubusercontent.com/assets/5161278/5893387/4d3c3f94-a4ea-11e4-9e0b-272b80ef368f.png)

Thank you!

**Comment by JHooverman** [comment]
Thank you @cranes-bill! I will update the Fergris theme tomorrow. Would you please let me know about the source of the icons of the new cyanotype theme? We will have to take about the licencing.

**Comment by cranes-bill** [comment]
OK, thank you! About the icons, i've extracted it some times ago, but not sure right now from where, so i will check tommorrow and then tell you.

**Comment by cranes-bill** [comment]
Well checked, and the source of the icons is: **gnome-icon-theme-symbolic** [(here for example)](http://dl.fedoraproject.org/pub/fedora/linux/development/rawhide/source/SRPMS/g/gnome-icon-theme-symbolic-3.12.0-2.fc21.src.rpm), it's also available in any Linux distribution repository. That's it. Thanks for the support!

**Comment by JHooverman** [comment]
@cranes-bill: What is the name of the new theme? Cyanotype or Blueprint?

**Comment by JHooverman** [comment]
Done! Thank you for your excellent work!

**Comment by cranes-bill** [comment]
I also thank you very much!
