### ISSUE TITLE
Just experiment

### ISSUE THREAD

**Issue by cranes-bill** [QupZilla/qupzilla-plugins#53]
So, i'm absolutely not familiar with programming and maybe this is a nonsense plug-in. It just add context menu option to paste QupZilla version when content is editable. 
**example:**
```
QupZilla: 1.8.8;
WebKit version: 537.21;
Qt version: 4.8.5
```
I just built it to test if i can do it, and just after reading few tutorials (_of course that's not a problem with my excellent English_ :smile:) and perhaps the developers might will seeing some bullshits inside the source...
However it works to me, so i decided to share it here [:package:](https://yadi.sk/d/pRvhVftvkJsyV).
That's it,
Regards

**Comment by nowrep** [comment]
So you just made a plugin for easier bug reporting? :D Good job ;)

**Comment by cranes-bill** [comment]
I hope you will be thinking the same after when you have seeing into the source!

**Comment by nowrep** [comment]
I saw it .. it's pretty bad, but if it works for you then why not :D

**Comment by cranes-bill** [comment]
Ha, ha, ha, i was not expecting more...
Ok, thanks for your time!
So i'm closing this...
