### ISSUE TITLE
Auto-scroll plugin doesn't work horizontally

### ISSUE THREAD

**Issue by nekoswag** [QupZilla/qupzilla-plugins#74]
>QupZilla 2.2.1 on openSUSE Tumbleweed 20171214

The automatic scroll plugin that activates with middle-click can only scroll vertically (up-down) but not horizontally (left-right).

This makes it cumbersome or useless for images that are too large to fit on the screen.

**Comment by nowrep** [comment]
Fixed in 2.2.2

**Comment by nekoswag** [comment]
oh okay :)
