### ISSUE TITLE
Videoner with MPV player

### ISSUE THREAD

**Issue by potholiday** [QupZilla/qupzilla-plugins#75]
This is not a bug reporting but I have successfully played a video with [mpv](https://mpv.io/) using videoner plugin. I followed all the steps in this [tutorial](https://github.com/QupZilla/qupzilla-plugins/wiki/Videoner) except the executable file looks like this

```
#!/bin/sh
mpv --cache=1024 --ytdl-format=22 $1
```

**Comment by cranes-bill** [comment]
That depends from **mpv** and the relevant video file. For example [here](https://www.quirksmode.org/html5/tests/video.html), your script works for me. Also, due to cache settings, you should wait a bit until video starts.

**Comment by potholiday** [comment]
I have a spotty internet connection and for me caching helps. Eventhough I am using qupzilla for past one year, only now I saw videoner. Till now I was using `GTK youtube viewer` app for streming youtube videos and after videoner I dont have to copy and pate youtube urls. Thank you for this and this makes life easier. By the way we can stream with vlc also

```
#!/bin/sh
vlc --preferred-resolution 240  $1
```

I think I should close this "issue" now.
